meta_product_name: "Pixel et Béchamel"
meta_title: "Pixel et Béchamel"
meta_description: "Pixel et Béchamel"
meta_image: "cappucino.png"                       # should exist in `app/assets/images/`


